title: Nithissh's Blogs
description: Just a guy who loves to learn things around
url: https://blog.nithissh.xyz
baseurl: ''
paginate: 5
paginate_path: /page/:num/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:year/:month/:day/:title/
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-archives
- jekyll-pagination

pagination:
  enabled: true
  per_page: 10
  permalink: '/page:num/'
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

jekyll-archives:
  enabled:
  - year
  layouts:
    year: year-archive
  permalinks:
    year: /:year/
collections:
  tags:
    output: true
    permalink: /tags/:name/
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: tags
  values:
    layout: tag
- scope:
    path: ''
  values:
    layout: default
navigation:
- title: Home
  url: /
- title: About Me
  url: /about/
- title: My CVEs
  url: /my-cves/
- title: Archive
  url: /archive/
- title: Categories
  url: /categories/
